### PR TITLE
112 fix dialog cancel buttons

### LINKED ISSUE #112: Fix Dialog Cancel Buttons
# Bug Report

## Description

Some dialogs still submit (!!) when cancelling them.

## Proposed Solution
- [ ] Dialogs should not close themselves before submitting.
- [ ] Dialogs should disable all interaction while submitting.
- [ ] Dialogs should re-enable all interaction after submitting failed.
- [ ] Dialogs should close after successful submitting.
- [ ] Check entire UIs dialogs for this error, I think it was the transfer dialog

### PR DESCRIPTION
**Pull request by richardtreier**
closes #112 

depends on #116

- fix transfer dialog submitting on cancel
- fix transfer dialog validation not working
- refactored transfer dialog to angular forms
- renamed transfer dialog to contract-agreement-transfer-dialog
- add data-address-type-select

### CODE REVIEW

File: src/modules/edc-demo/components/contract-viewer/contract-viewer.component.ts [hunk 1]
```diff
@@ -68,28 +64,16 @@ export class ContractViewerComponent implements OnInit {
...
-          this.startPolling(transferId, contract.id!);
-        },
-        error: (error) => {
-          console.error(error);
-          this.notificationService.showError('Error initiating transfer');
-        },
+      .pipe(filter((it) => !!it))
+      .subscribe((result: ContractAgreementTransferDialogResult) => {
+        this.startPolling(result.transferProcessId, result.contractId);
       });
```
Comment (efiege) [inline src/modules/edc-demo/components/contract-viewer/contract-viewer.component.ts:77]: No error message, when the transfer fails?

File: CHANGELOG.md [hunk 2]
```diff
@@ -25,7 +25,12 @@ the detailed section referring to by linking pull requests or issues.
 #### Removed
 
 #### Fixed
+
 - Placeholder URLs missing "/control/" path
+- Fixed Keyword select not adding keywords on input field blur, causing loss of
+  input.
+- Fixed transfer dialog submitting on cancel
+- Fixed transfer dialog validation not working
```
Comment (efiege) [inline CHANGELOG.md:34]: Introduced reusability of Data Address Form?

**Review by efiege — APPROVED** [review]
dependabot.yml empty but not deleted?

File: CHANGELOG.md (hunk 2 above)
Comment (richardtreier) [reply CHANGELOG.md:34]: I'd say that's too technical to be relevant. I'd rather focus on "product related" changes we got done. Despite producing code, the above refactoring was very natural

File: src/modules/edc-demo/components/contract-viewer/contract-viewer.component.ts (hunk 1 above)
Comment (richardtreier) [reply src/modules/edc-demo/components/contract-viewer/contract-viewer.component.ts:77]: This code block is only reached after success. The dialog handles errors / success and only closes itself with the success result message when it did successfully initiate the transfer. This is so that the dialog doesn't have to close to submit its data.

File: CHANGELOG.md (hunk 2 above)
Comment (richardtreier) [reply CHANGELOG.md:34]: Oh and we did not introduce reusability of the data address form
