### PR TITLE
Revert Back Logic on Create and Edit Asset

### LINKED ISSUE #774: Edit asset not working
**Describe the bug**
When editing an asset, after clicking the update button the asset is not updated and all buttons are greyed out. The user needs to press escape or refresh page to exit the edit dialog.

**To Reproduce**
1. Go to Assets
2. Select an asset and open the details.
3. Click on edit button.
4. Make changes and click update

**Expected behavior**
The asset details are updated, the user is informed about the operation result, the edit window is closed.

**Screenshots**

**MDS Versions (please complete the following information):**
 - EDC: [9.0.0]
 - EDC-UI: [4.0.0]

### PR DESCRIPTION
**Pull request by illfixit**
_What issues does this PR close?_
closes #1409 Revert back logic on Create Asset button
closes #774 Edit asset not working

### Edit Dialog:
image

### A few changes in the asset:
image

### Updated + Automatically refresh in both grid of assets and the dialog (relevant for #774)
image

### Properly edit again without closing the original dialog:
image

### Create Asset Dialog works as before and supports on-request option:
image

```[tasklist]
### Checklist
- [x] The PR title is short and expressive.
- [x] I have updated the CHANGELOG.md. See [changelog_update.md](https://github.com/sovity/authority-portal/tree/main/docs/dev/changelog_updates.md) for more information.
- [ ] I have updated the Deployment Migration Notes Section in the CHANGELOG.md for any configuration / external API changes.
- [x] I have performed a **self-review**
```

### CODE REVIEW

File: src/app/component-library/data-address/data-address-type-select/data-address-type-select-items.ts [hunk 1]
```diff
@@ -6,6 +6,13 @@ export const dataAddressTypeSelectItems = (
 ): DataAddressTypeSelectItem[] => {
   const items: DataAddressTypeSelectItem[] = [];
 
+  if (type.startsWith('Datasource')) {
+    items.push({
+      id: 'On-Request',
+      label: '"On Request" Data Offer',
+    });
+  }
```
Comment (kulgg) [inline src/app/component-library/data-address/data-address-type-select/data-address-type-select-items.ts:14]: image

This makes the create data offer form scuffed since both use this data-address-type-select-items thing. Need to find a way to only have this for the dialog

File: src/app/routes/connector-ui/asset-page/asset-edit-dialog/form/model/asset-datasource-form-model.ts [hunk 2]
```diff
@@ -0,0 +1,49 @@
+import {
+  FormArray,
+  FormControl,
+  FormGroup,
+  ɵFormGroupValue,
+} from '@angular/forms';
+import {UiDataSourceHttpDataMethod} from '@sovity.de/edc-client';
+// import {DataAddress} from 'src/app/component-library/edit-asset-form/edit-asset-form/form/model/data-address';
```
Comment (kulgg) [inline src/app/routes/connector-ui/asset-page/asset-edit-dialog/form/model/asset-datasource-form-model.ts:8]: can be removed

File: src/app/routes/connector-ui/asset-page/asset-page/asset-page.component.html [hunk 3]
```diff
@@ -18,17 +18,15 @@
...
+    <button
       id="create-button"
       color="primary"
       mat-raised-button
       style="margin-top: 8px; height: 44px"
-      routerLink="/create-asset">
-      <div class="flex justify-center items-center h-full gap-1">
-        <mat-icon class="mt-[1px]">add_circle_outline</mat-icon>
-        Create asset
-      </div>
```
Comment (kulgg) [inline src/app/routes/connector-ui/asset-page/asset-page/asset-page.component.html:30]: we can keep this part inside the button it just aligns the icon nicely

**Review by kulgg — CHANGES_REQUESTED** [review]

**Review by kulgg — APPROVED** [review]
LGTM
