### PR TITLE
Unify date formats and fix of manually editing dates

### LINKED ISSUE #802: Manually editing dates shows strange behavior
### Description - What happened? *

First report: `The policy creation page does not allow manual editing of the date field in the date wizard functionality.`

My own tests: Changing the year or other details always changes the month and day.

[screen-capture (7).webm](https://github.com/user-attachments/assets/66c5b11e-259d-49f2-9ab4-1cd02e763bde)

### Expected Behavior *

Should also be editable manually without major problems.

### Observed Behavior *

See Description.

### Steps to Reproduce

See Description video.

### Context Information

ui 4.1.2

### Relevant log output

_No response_

### Screenshots

_No response_

### LINKED ISSUE #803: Date format differs between pages
### Description - What happened? *

```
When we create policies with policy expressions using evaluation time, we have a DD/MM/YYYY format.
After creating a policy, we can see the evaluation time in the YYYY/MM/DD format on the policy page.
Note : Contract signed also we have YYYY/MM/DD format contract view page
```

### Expected Behavior *

Same date format should implemented for all pages

### Observed Behavior *

Date format differs between pages

### Steps to Reproduce

```
- Navigate EDC UI application
- Click on create policy with evaluation time DD/MM/YYYY format.
- After creating a policy, we can see the evaluation time in the YYYY/MM/DD format on the policy page
```

### Context Information

_No response_

### Relevant log output

_No response_

### Screenshots

Creating policy DD/MM/YYYY
image

Policy created (Policy Page) YYYY-MM-DD
image

Contract Agreement YYYY-MM-DD
image

### LINKED ISSUE #810: Hover timestamps are 12h format without AM/PM
### Description - What happened? *

Hover timestamps are 12h format without AM/PM indication, thus they show 02:18 instead of 14:18.

**Real expected timestamp:**
image

**Hover Timestamp:**
image

### Expected Behavior *

Hover timestamps should display the correct time.

### Observed Behavior *

Hover timestamps show 12 hour format without AM/PM, so all data from 13:00 onwards in the hover is shifted backwards by 12 hours. -> 02:18 instead of 14:18

### Steps to Reproduce

_No response_

### Context Information

_No response_

### Relevant log output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by illfixit**
_What issues does this PR close?_
closes #802 Manually editing dates shows strange behavior
closes #803 Date format differs between pages
closes #810 Hover timespamps are 12h

### Create Policy
image

Result:
image

### Timespan Restriction
both using calender
image

Intermediate step
image

Result
image

one date chosen via calender
image

second date inputted manually
image

intermediate step
image

Result
image

### Assets Page (Dialog -> Signed)
image

### Policies page
image

### Catalog Browser (Dialog -> Temporal Coverage + Policy)
image

### Contracts (Dialog -> Signed + Policy)
image

### Contracts page
image

### Transfer history page
image

```[tasklist]
### Checklist
- [x] The PR title is short and expressive.
- [x] I have updated the CHANGELOG.md. See [changelog_update.md](https://github.com/sovity/authority-portal/tree/main/docs/dev/changelog_updates.md) for more information.
- [ ] I have updated the Deployment Migration Notes Section in the CHANGELOG.md for any configuration / external API changes.
- [x] I have performed a **self-review**
```

### CODE REVIEW

File: src/app/component-library/policy-editor/editor/policy-form-expression-constraint/policy-form-expression-constraint.component.ts [hunk 1]
```diff
@@ -7,6 +9,7 @@ import {TreeNode} from '../tree';
 @Component({
   selector: 'policy-form-expression-constraint',
   templateUrl: './policy-form-expression-constraint.component.html',
+  providers: [{provide: DateAdapter, useClass: CustomDateAdapter}],
```
Comment (richardtreier) [inline src/app/component-library/policy-editor/editor/policy-form-expression-constraint/policy-form-expression-constraint.component.ts:12]: please provide this globally in the AppModule or SharedModule where other Angular Material config resides, so it has to be provided only once

File: src/app/component-library/policy-editor/editor/recipes/timespan-restriction-dialog/timespan-restriction-dialog.component.ts [hunk 2]
```diff
@@ -1,15 +1,18 @@
...
 import {UiPolicyExpression} from '@sovity.de/edc-client';
+import {CustomDateAdapter} from 'src/app/core/adapters/custom-date-adapter';
 import {validDateRange} from '../../../../../core/validators/valid-date-range-optional-end';
 import {ValidationMessages} from '../../../../../core/validators/validation-messages';
 import {buildTimespanRestriction} from './timespan-restriction-expression';
 
 @Component({
   selector: 'timespan-restriction-dialog',
   templateUrl: './timespan-restriction-dialog.component.html',
+  providers: [{provide: DateAdapter, useClass: CustomDateAdapter}],
```
Comment (richardtreier) [inline src/app/component-library/policy-editor/editor/recipes/timespan-restriction-dialog/timespan-restriction-dialog.component.ts:15]: duplicate

File: src/app/core/adapters/custom-date-adapter.ts [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+        date.getFullYear(),
+        date.getMonth(),
+        date.getDate(),
+        date.getHours(),
+        date.getMinutes(),
+        date.getSeconds(),
+        date.getMilliseconds(),
+      ),
+    );
+    displayFormat = Object.assign({}, displayFormat, {timeZone: 'utc'});
```
Comment (richardtreier) [inline src/app/core/adapters/custom-date-adapter.ts:30]: I'm not sure this makes sense

File: src/app/core/adapters/custom-date-adapter.ts [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+
+    const dtf = new Intl.DateTimeFormat(this.locale, displayFormat);
+    return dtf.format(date).replace(/[\u200e\u200f]/g, '');
```
Comment (richardtreier) [inline src/app/core/adapters/custom-date-adapter.ts:33]: prefer date-fns methods, we should not start writing custom date handling if avoidable:

https://www.phind.com/search?cache=xd7y1x79v8e56qvqith510z8

same for the format

**Review by richardtreier — CHANGES_REQUESTED** [review]

**Review by richardtreier — APPROVED** [review]
lgtm
